trigger:
- main

#pool:
#  name: Default

pool:
  vmImage: ubuntu-latest

# Include the repo of the helper and CommonConstants libraries
resources:
  repositories:
    - repository: helpers
      type: github
      name: anandsanjayreddy/buildlibrary
      endpoint: github.com_anandsanjayreddy
# Parameters to be give while running the pipeline

# Variables used in the pipeline that pulled fom CommonConstants Library
variables:
  - template: CommonConstants.yml@helpers
# Initalise
steps:
- bash: 
    echo "Selected module - ${{ variables.module }}"
- template: InstallSSHKey.yml@helpers    
- template: GetSource.yml@helpers      #Using the Getsource library
  parameters:
    branch: ${{ variables.dev_branch }}
    gitUrl: ${{ variables.gitUrl }}
- task: CmdLine@2
  inputs:
    script: |
      version=`jq .version ./azurepipelinetesting/package.json | tr -d '"'`;
      IFS='.' 
      read -ra versionarray <<< $version
      reducedMinorVer=$(expr ${versionarray[1]} - 1)
      IFS=''
      releaseVersion="${versionarray[0]}.$reducedMinorVer"
      releaseBranchName='release-'$releaseVersion
      echo $releaseBranchName
      echo "##vso[task.setvariable variable=releaseBranchName]$releaseBranchName"
- ${{ if eq(variables.branchName, '') }}:
  - template: GetSource.yml@helpers      #Using the Getsource library
    parameters:
      branch: $(releaseBranchName)
      gitUrl: ${{ variables.gitUrl }}
- ${{ if not(eq(variables.branchName, '')) }}:
  - template: GetSource.yml@helpers      #Using the Getsource library
    parameters:
      branch: ${{ variables.branchName }}
      gitUrl: ${{ variables.gitUrl }}
- bash: 
    echo Merging release to master.
- ${{ if eq(variables.branchName, '') }}:
  - template: Merge.yml@helpers        #Using the Merge library
    parameters:
      source: $(releaseBranchName)
      destination: ${{ variables.master_branch }}
- ${{ if not(eq(variables.branchName, '')) }}:
  - template: Merge.yml@helpers        #Using the Merge library
    parameters:
      source: ${{ variables.branchName }}
      destination: ${{ variables.master_branch }} 
- bash:
    cd ./azurepipelinetesting;
    git push origin -u ${{ variables.master_branch }}
